version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: fastapi_dbnew
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: fastapi_clean
      MYSQL_USER: appuser
      MYSQL_PASSWORD: secret
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psecret"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s

  redis:
    image: redis:latest
    container_name: fastapi_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      ENV: dev
      DB_USER: root
      DB_PASSWORD: secret
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: fastapi_clean

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: fastapi_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "8888:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
  redis_data: