from enum import Enum

class ErrorCodeEnum(Enum):
    VALIDATION_ERROR = 'VALIDATION_ERROR'
    STORE_DATA_FAILED = 'STORE_DATA_FAILED'
    COUPON_NOT_FOUND = 'COUPON_NOT_FOUND'
    GET_REVIEWS_FAILED = 'GET_REVIEWS_FAILED'